#!/usr/bin/env ruby

# Uses ffmpeg to create clips from a video file.
#
#== Usage:
# create-clips [options] <video_file> <output_dir>

require 'video_scripts'

options = VideoScripts::ClipOptions.new
options.parse!

timestamp_file = VideoScripts::TimestampFile.new(options.timestamp_file)
clips = timestamp_file.parse!

clips.map do |clip|
  clip.title = timestamp_file.title
  clip.file = options.input_file
  clip.output_dir = options.output_dir
end

if options.dry_run
  clips.each do |clip|
    puts clip.command
  end
else
  clips.each do |clip|
    puts clip.clip!
  end
end
