#!/usr/bin/env ruby
# frozen_string_literal: true

# Generate FFMETADATAFILE to insert chapters into an MP4 file
#
# @see https://ikyle.me/blog/2020/add-mp4-chapters-ffmpeg
# @see https://ffmpeg.org/ffmpeg-formats.html (search for "FFMETADATA")
#
# == Input file format:
# 00:01:00 Some Title
# 00:03:44 Some other title
# 01:20:29 Another thing
# 01:39:41 The End
#
# == Usage:
# generate-mp4-chapter-metadata ChapterDetails.txt
#
# == Retrieving current Chapter Information
# ffmpeg -i INPUT -f ffmetadata FFMETADATAFILE
#
# == Inserting new Chapter Information
# ffmpeg -i INPUT -i FFMETADATAFILE -map_metadata 1 -codec copy OUTPUT

require 'video_scripts'

Options = Struct.new(:title, :timestamp_file)

options = Options.new
options.title = ''
options.timestamp_file = ARGV[0]

timestamp_file = VideoScripts::TimestampFile.new(options.timestamp_file)
clips = timestamp_file.parse!

options.title = timestamp_file.title

metadata_builder = VideoScripts::FfmetadataBuilder.new(clips, options.title)

File.open('FFMETADATAFILE', 'w') do |file|
  file.write(metadata_builder.build)
end
